[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
"c-call-rust",
"rust-call-c",
"rust-call-c-by-cc",
"rust-call-c-by-bindgen"
]

[workspace.dependencies]
cc = "1.0.73"
bindgen = "0.66.1"